version: '3'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
